### ISSUE TITLE
How to dynamically re-size child frame

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#289]
Hi @seagle0128 ,

I have pulled your latest changes and I wanted to bring this to your notice.
I have been using kubel and the transient frame is bigger and it wraps in the childframe.

![image](https://user-images.githubusercontent.com/23665525/112038870-5ca5b280-8b11-11eb-8d72-0bcaa4b6ce95.png)

How to solve this?

**Comment by seagle0128** [comment]
Thanks for your feedback!
It's an experimental feature. To disable it, you can:

```elisp
;; In custom.el
(setq centaur-completion-style 'minibuffer)
```
or
```elisp
(setq ivy-read-action-function 'ivy-read-action-by-key)
(setq hydra-hint-display-type 'minibuffer)
```

**Comment by seagle0128** [comment]
I committed a patch to disable the warp-lines in the child frame.

**Comment by CsBigDataHub** [comment]
@seagle0128 I just tested the patch after pulling your latest changes. yet I still see the line wraps.

**Comment by seagle0128** [comment]
Then need one more patch to fix transient-posframe.

**Comment by CsBigDataHub** [comment]
@seagle0128 tested your patch, I do not see any difference. The behaviour still persists.

**Comment by seagle0128** [comment]
It's an issue of `transient-posframe`. I got a workaround to fix it anyway.

**Comment by CsBigDataHub** [comment]
> It's an issue of `transient-posframe`. I got a workaround to fix it anyway. Please try the latest version.
> 
> NOTE: `(setq centaur-completion-style 'childframe)` in `custom.el` to enable.

Works perfectly. Thanks much.

**Comment by seagle0128** [comment]
Welcome!
