### ISSUE TITLE
Wrong type argument: number-or-marker-p at startup

### ISSUE THREAD

**Issue by ettomatic** [seagle0128/.emacs.d#86]
Getting this in messages at startup:
```
/: Wrong type argument: number-or-marker-p, "CENTAUR EMACS - Enjoy Programming & Writing"
Quit [2 times]
```

Tried using the default `custom.el` and `custom-post.el` with no luck.

**Comment by seagle0128** [comment]
Would you please try the latest Centaur with `dashboard` package? It's a regression issue in `dashboard` package, but has been already fixed.

**Comment by ettomatic** [comment]
ok it worked. Thank you very much. Slightly confused by the fact that a normal `M-X centaur-update` didn't fix the issue.

**Comment by seagle0128** [comment]
Well, the `emacs-dashboard` package was broken in one release and the issue was fixed soon, but the new build may need a few hours to be ready. That's the root cause.

**Comment by AmiZya** [comment]
Can you please post how did you fix it ?

**Comment by seagle0128** [comment]
@AmiZya That's an compatibility issue between `Centaur` and `dashboard`. The new features `file icons` and `navigator` are added into `dashboard`, so `Centaur` should be updated accordingly.
